export const queryKeys = {
  systemStatus: ['system', 'status'] as const,
  profile: ['profile'] as const,
  opportunities: ['opportunities'] as const,
  opportunity: (id: string) => ['opportunities', id] as const,
  opportunityAttachments: (id: string) => ['opportunities', id, 'attachments'] as const,
  opportunityComments: (id: string) => ['opportunities', id, 'comments'] as const,
  opportunityAgentRuns: (id: string) => ['opportunities', id, 'agent-runs'] as const,
  activeCoverLetterRun: (id: string) => ['opportunities', id, 'cover-letter', 'active'] as const,
  inboxCounts: ['inbox', 'counts'] as const,
  inboxSortedCounts: ['inbox', 'sorted-counts'] as const,
  inboxList: (window: string) => ['inbox', window] as const,
  inboxEmail: (id: string) => ['inbox', 'email', id] as const,
  inboxEmailOpportunities: (id: string) => ['inbox', 'email', id, 'opportunities'] as const,
  inboxStatus: ['inbox', 'status'] as const,
  inboxActiveScan: ['inbox', 'scan', 'active'] as const,
  workExperiences: ['work-experiences'] as const,
  workExperience: (id: string) => ['work-experience', id] as const,
  workExperienceProjects: (id: string) => ['work-experience-projects', id] as const,
  resumes: ['profile', 'resumes'] as const,
  activeParseRun: ['profile', 'resumes', 'parse-active'] as const,
}
